# Generated by Django 5.2.8 on 2026-05-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-date_joined'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='can_check_in_out',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='can_manage_bookings',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='can_manage_rooms',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='can_process_payments',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staffprofile',
            name='emergency_contact',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_name',
            field=models.CharField(blank=True, help_text='Name of emergency contact person', max_length=150),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=15),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='emergency_contact_relation',
            field=models.CharField(blank=True, help_text='Relationship to emergency contact', max_length=50),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='employee_notes',
            field=models.TextField(blank=True, help_text='Internal notes about this staff member (not visible to them)'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='hire_date',
            field=models.DateField(blank=True, help_text='Date when the staff member was hired', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='can_check_in_out',
            field=models.BooleanField(default=False, help_text='Can check guests in and out'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_bookings',
            field=models.BooleanField(default=False, help_text='Can approve, cancel, and manage bookings'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_rooms',
            field=models.BooleanField(default=False, help_text='Can add, edit, and delete rooms'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_staff',
            field=models.BooleanField(default=False, help_text='Can create and manage staff accounts'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_process_payments',
            field=models.BooleanField(default=False, help_text='Can process and record payments'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=False, help_text='Can view financial and operational reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='deactivated_at',
            field=models.DateTimeField(blank=True, help_text='When the account was deactivated', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='deactivation_reason',
            field=models.TextField(blank=True, help_text='Reason for account deactivation'),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, help_text='Department or section', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False, help_text="Whether the user's identity has been verified"),
        ),
        migrations.AddField(
            model_name='user',
            name='password_changed_at',
            field=models.DateTimeField(blank=True, help_text='When the password was last changed', null=True),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning Shift (6AM - 2PM)'), ('afternoon', 'Afternoon Shift (2PM - 10PM)'), ('night', 'Night Shift (10PM - 6AM)'), ('flexible', 'Flexible Hours')], default='morning', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, help_text='Guest address (optional)', verbose_name='Physical Address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, error_messages={'unique': 'A user with this email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff_active',
            field=models.BooleanField(default=True, help_text='Designates whether this staff member can access the system', verbose_name='Staff Account Active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login_ip',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_count',
            field=models.IntegerField(default=0, verbose_name='Total Logins'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(db_index=True, help_text='Format: +255712345678 or 0712345678', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Staff position or job title', max_length=100, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('guest', 'Guest'), ('staff', 'Staff'), ('manager', 'Hotel Manager'), ('admin', 'Admin')], db_index=True, default='guest', help_text='User role determines access permissions', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Internal staff identification number', max_length=20, null=True, unique=True, verbose_name='Employee ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Auto-generated from email if not provided', max_length=150, null=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'is_active'], name='users_role_a8f2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
    ]
