# Generated by Django 6.0.5 on 2026-05-06 14:52

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference_id', models.CharField(db_index=True, editable=False, help_text='Unique booking reference (e.g., VETA-2026-0042)', max_length=20, unique=True)),
                ('check_in', models.DateField(help_text='Check-in date')),
                ('check_out', models.DateField(help_text='Check-out date')),
                ('nights', models.IntegerField(editable=False, help_text='Number of nights', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_night', models.DecimalField(decimal_places=2, editable=False, help_text='Room price at time of booking', max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Total amount in TZS', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('checked_in', 'Checked In'), ('checked_out', 'Checked Out'), ('cancelled', 'Cancelled')], db_index=True, default='pending', help_text='Current booking status', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('refunded', 'Refunded')], db_index=True, default='unpaid', help_text='Payment status', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('checked_out_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('guest_count', models.IntegerField(default=1, help_text='Number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('special_requests', models.TextField(blank=True, help_text='Special requests from guest')),
                ('cancellation_reason', models.TextField(blank=True, help_text='Reason for cancellation')),
                ('staff_notes', models.TextField(blank=True, help_text='Internal staff notes')),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
    ]
