# Generated by Django 6.0.5 on 2026-05-06 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guest',
            field=models.ForeignKey(help_text='Guest who made the booking', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='processed_by',
            field=models.ForeignKey(blank=True, help_text='Staff member who processed the booking', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(help_text='Booked room', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='rooms.room'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'check_in'], name='bookings_status_3aab84_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['reference_id'], name='bookings_referen_d90c58_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['guest', 'status'], name='bookings_guest_i_0048dc_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['check_in', 'check_out'], name='bookings_check_i_759ffa_idx'),
        ),
    ]
