# Generated by Django 6.0.5 on 2026-05-06 14:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('suite', 'Suite Room'), ('family', 'Family Room'), ('deluxe', 'Deluxe Room')], max_length=50, unique=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('base_capacity', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('max_capacity', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('amenities', models.TextField(blank=True, help_text='Separate amenities with commas (e.g., WiFi, TV, AC)')),
            ],
            options={
                'verbose_name': 'Room Type',
                'verbose_name_plural': 'Room Types',
                'db_table': 'room_types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('room_number', models.CharField(db_index=True, help_text='Room number or identifier', max_length=10, unique=True)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('suite', 'Suite Room'), ('family', 'Family Room'), ('deluxe', 'Deluxe Room')], db_index=True, help_text='Type of room', max_length=20)),
                ('floor', models.IntegerField(default=1, help_text='Floor number')),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night in TZS', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('capacity', models.IntegerField(default=1, help_text='Maximum number of guests', validators=[django.core.validators.MinValueValidator(1)])),
                ('description', models.TextField(blank=True, help_text='Room description and features')),
                ('image', models.ImageField(blank=True, help_text='Room photo (optional)', null=True, upload_to='rooms/')),
                ('status', models.CharField(choices=[('available', 'Available'), ('occupied', 'Occupied'), ('maintenance', 'Maintenance'), ('reserved', 'Reserved')], db_index=True, default='available', help_text='Current room status', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Internal notes (not visible to guests)')),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'db_table': 'rooms',
                'ordering': ['floor', 'room_number'],
                'indexes': [models.Index(fields=['status', 'room_type'], name='rooms_status_75ed3e_idx'), models.Index(fields=['price_per_night'], name='rooms_price_p_db2697_idx')],
            },
        ),
        migrations.CreateModel(
            name='RoomImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rooms/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='rooms.room')),
            ],
            options={
                'verbose_name': 'Room Image',
                'verbose_name_plural': 'Room Images',
                'db_table': 'room_images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
    ]
